### ISSUE TITLE
Text like `file:///c:/temp/foo.txt` parsed as link

### ISSUE THREAD

**Issue by shapel** [tarleb/jira-wiki-markup#6]
Hello
Below you can find one more item from me ;)

**Input**
pandoc version 2.12
` echo "file:///c:/temp/foo.txt"  | pandoc -f jira -t json | jq`

**Output**
```
{
  "pandoc-api-version": [
    1,
    22
  ],
  "meta": {},
  "blocks": [
    {
      "t": "Para",
      "c": [
        {
          "t": "Link",
          "c": [
            [
              "",
              [],
              []
            ],
            [
              {
                "t": "Str",
                "c": "file:///c:/temp/foo.txt"
              }
            ],
            [
              "file:///c:/temp/foo.txt",
              ""
            ]
          ]
        }
      ]
    }
  ]
}
```

Expected the same output like for escaped  one:
`echo "file:\/\/\/c:/temp\/foo.txt"  | pandoc -f jira -t json | jq`
```
{
  "pandoc-api-version": [
    1,
    22
  ],
  "meta": {},
  "blocks": [
    {
      "t": "Para",
      "c": [
        {
          "t": "Str",
          "c": "file:///c:/temp/foo.txt"
        }
      ]
    }
  ]
}
```

**Comment by tarleb** [comment]
> Below you can find one more item from me ;)

Thanks, I guess ;P

So you mean that the `file://` schema should not be recognized as a URL? It's one of the things where Jira seems inconsistent: the preview turns it into a link, but in the end it generally isn't? I'm tempted to leave it as it is, simply because I'm not sure if people rely on the current behavior.

**Comment by shapel** [comment]
As far as I understand according to spec (https://jira.atlassian.com/secure/WikiRendererHelpAction.jspa?section=links) text of type `file://` should be a parse as a link only if it is enclosed in "[''] '.

**Comment by tarleb** [comment]
It does seem like that, but the same can be said for emails, where it's clearly not true. The problem with the spec is that it's unclear, ambiguous, and, if I remember correctly, partly wrong.

(Excuse my frustration here. Jira markup is rather wacky as far as markup goes, and implementing this library took a lot of reverse engineering. Irony has it that I wrote the package because I was tired of fighting the subtleties of Jira, but then changed jobs shortly after and now no longer need it. And now I'm maintaining this library :man_facepalming: ) 

Anyway, I think you are right in that rarely anyone would use this `file:` feature; I'm not even sure if it still works on all Jira variants, so let's change it.

FWIW, this is the kind of thing that can be worked around with a pandoc [Lua filter](https://pandoc.org/lua-filters.html). E.g.

``` lua
-- unlink `file://` links
function Link (link)
  if link.target:match '^file://' then
    return link.content
  end
end
```

So you won't have to wait for the next pandoc release.

**Comment by shapel** [comment]
@tarleb for sure maintaining such a parser is a tricky task.
Thanks for your effort!
